export const places = [
  {
    id: 1,
    name: "Pokemon Center Mega Tokyo",
    interest: "Pokemon",
    rating: 4.8,
    x: 70,
    y: 35,
    img: "🎮",
  },
  {
    id: 2,
    name: "Pokemon Cafe",
    interest: "Pokemon",
    rating: 4.7,
    x: 45,
    y: 45,
    img: "☕",
  },
  {
    id: 3,
    name: "Nintendo Tokyo",
    interest: "Nintendo",
    rating: 4.9,
    x: 55,
    y: 55,
    img: "🕹️",
  },
  {
    id: 4,
    name: "Akihabara District",
    interest: "Anime",
    rating: 4.6,
    x: 65,
    y: 65,
    img: "🏙️",
  },
  {
    id: 5,
    name: "Ghibli Museum",
    interest: "Anime",
    rating: 4.9,
    x: 30,
    y: 40,
    img: "🎬",
  },
  {
    id: 6,
    name: "Nintendo World Store",
    interest: "Nintendo",
    rating: 4.7,
    x: 40,
    y: 70,
    img: "⭐",
  },
];
